### ISSUE TITLE
Can't use Sass Maps

### ISSUE THREAD

**Issue by rizqinizamil** [pierreburel/sass-rem#6]
When I put Sass Maps like this

```
@include rem((
    margin: 20px 1rem,
    padding: 10px
  ));
```

Then show error like `required parameter $values is missing in call to mixin rem`

**Comment by pierreburel** [comment]
Hi,

what version of Sass do you use? Any other library (like Bourbon)?

**Comment by rizqinizamil** [comment]
Hi, thanks for your respond.
I use `Sass 3.4.18 (Selective Steve)` and also use Susy and [libsass-compass-vertical-rhythm](https://github.com/neoeno/libsass-compass-vertical-rhythm).

**Comment by pierreburel** [comment]
Hi,

it seems that  [libsass-compass-vertical-rhythm](https://github.com/neoeno/libsass-compass-vertical-rhythm) defines a [rem mixin](https://github.com/neoeno/libsass-compass-vertical-rhythm/blob/master/lib/compass_rhythm/_units.scss#L169), which must override sass-rem's one (depending of your `@import` order). This is the one reporting the error you have.

I decided not to namespace sass-rem mixin and function for simplicity, but this way it can't works with other libraries doing the same thing with their own implementation.

Since you're not the first reporting this, I'll add a disclaimer in the README to explain that, and maybe provide an alternate namespaced version (I just need to find a name).
